(async function () {
  const $ = id => document.getElementById(id);
  const results = $('qaResults');
  const waitFor = async check => {const start=Date.now();while(!check()){if(Date.now()-start>7000)throw new Error('Timed out: '+check);await new Promise(resolve=>setTimeout(resolve,30));}};
  const ok = (check,name) => {if(!check)throw new Error(name);results.textContent+='PASS: '+name+'\n';};
  const scan = code => {$('mostradorScan').value=code;$('mostradorScan').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));};
  try {
    $('btnMostrador').click();
    await waitFor(()=>$('catSyncStatus').textContent.includes('Actualizado'));
    scan('7790000000013');scan('7790000000013');
    await waitFor(()=>document.querySelector('.mostrador-qty span')?.textContent==='2');
    ok($('mostradorTotal').textContent.includes('3.200'),'Repeated scans increment quantity');
    ok(JSON.parse(localStorage.getItem('kiosco_catalogo_v1')).c_fixture_1.stock===10,'Scanning does not discount stock');
    $('mostradorCobrar').click();
    await waitFor(()=>$('mostradorStatus').textContent.includes('Venta registrada'));
    ok(JSON.parse(localStorage.getItem('kiosco_catalogo_v1')).c_fixture_1.stock===8,'Confirmed ticket discounts stock');
    document.querySelector('[data-most-mode="consulta"]').click();
    scan('7790000000020');
    await waitFor(()=>document.querySelector('.mostrador-consulta h3'));
    ok(document.querySelector('.mostrador-consulta').textContent.includes('Milka'),'Consult mode shows selected product');
    document.querySelector('[data-most-mode="entrada"]').click();
    scan('7790000000020');
    await waitFor(()=>document.querySelector('[data-cost]'));
    document.querySelector('[data-plus]').click();document.querySelector('[data-plus]').click();
    ok(document.querySelector('.mostrador-qty span').textContent==='3','Receiving counts individual units');
    $('mostradorCobrar').click();
    await waitFor(()=>$('mostradorStatus').textContent.includes('Entrada registrada'));
    ok(JSON.parse(localStorage.getItem('kiosco_catalogo_v1')).c_fixture_2.stock===23,'Receiving adds rather than replaces stock');
    document.querySelector('[data-most-mode="venta"]').click();
    scan('7790000000013');
    await waitFor(()=>document.querySelector('.mostrador-qty span'));
    scan('7790000000044');
    await waitFor(()=>!$('mostradorAlta').hidden);
    $('mostradorNombre').value='Lapicera azul';$('mostradorCategoria').value='Libreria';
    $('mostradorPrecio').value=1000;$('mostradorCosto').value=400;$('mostradorStock').value=15;
    $('mostradorAlta').requestSubmit();
    await waitFor(()=>$('mostradorAlta').hidden && document.querySelectorAll('.mostrador-item').length===2);
    ok($('mostradorList').textContent.includes('Lapicera azul'),'Quick create retains existing basket and adds product');
    $('mostradorClose').click();$('btnMostrador').click();
    ok(document.querySelectorAll('.mostrador-item').length===2,'Closing and reopening preserves the basket');
    document.querySelector('[data-most-mode="tickets"]').click();
    await waitFor(()=>document.querySelector('.mostrador-ticket'));
    ok($('mostradorList').textContent.includes('3.200'),'Confirmed ticket is in shared history');
    $('mostradorClose').click();
    const homeButton=$('btnPrecios');homeButton.focus();
    for(const key of '7790000000013')homeButton.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));
    const enter=new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true});homeButton.dispatchEvent(enter);
    ok(enter.defaultPrevented,'Scanner Enter does not activate the focused home button');
    await waitFor(()=>$('mostradorOverlay').classList.contains('open'));
    ok(!$('priceOverlay').classList.contains('open'),'Global scan opens only Mostrador');
    $('mostradorClose').click();
    document.title='PASS: 11 scanner browser checks';
    results.textContent+='DONE: no production traffic or changes.\n';
  } catch(error) {results.textContent+='FAIL: '+error.stack;document.title='FAIL: scanner tests';}
})();
